import Head from 'next/head';
import Box from '../../components/primitives/Box';
import * as Layout from '../../components/primitives/Layout2';


export default function Home() {
  return (
      <>
        <Head>
          <title>BrightData </title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Layout.Shell layout="control-panel">
            <Box css={{ boxShadow: "inset -1px 0px #E0E3E6" }}/>
            <Layout.Page>

                <Layout.Section>
                    <Layout.Content layout="full">
                        <Box css={{backgroundColor: "red", width: "100%", height: "200px"}}></Box>
                    </Layout.Content>
                </Layout.Section>

                <Layout.Section>
                    <Layout.Content layout="overflow">
                        <Box css={{backgroundColor: "red", width: "100%", height: "200px"}}></Box>
                    </Layout.Content>
                </Layout.Section>

            </Layout.Page>
        </Layout.Shell>
      </>
  )
}

