import { styled } from '@stitches/react';
import type { NextPage } from 'next';
import Head from 'next/head';
import Cards from '../components/mock_components/Cards';
import LinkList from '../components/mock_components/LinkList';
import Nav from '../components/mock_components/Nav';
import Table from '../components/mock_components/table';

const Box = styled("div", {
    backgroundColor: "#E6E8EB"
})

const Shell = styled("div", {
    width: "100vw",
    height: "100vh",
    display: "grid",
    gridTemplateColumns: "80px 1fr",
    backgroundColor: "#F8F9FA",
    overflow: "clip",
})

const Page = styled("div", {
    width: "100%",
    height: "100%",
    display: "flex",
    flexDirection: "column",
    gap: "32px",
    overflowX: "hidden",
    overflowY: "auto"
})

const Section = styled("div", {
    width: "100%",
    height: "fit-content",
    // backgroundColor: "#F1F3F5",
    display: "flex",
    justifyContent: "center"
})

const Content = styled("div", {
    display: "grid",
    width: "100%",
    maxWidth: "1280px",
    paddingLeft: "clamp(12px, 12%, 128px)",
    paddingRight: "clamp(12px, 12%, 128px)",
    alignItems: "start",

    variants: {
        layout: {
            ['overflow']: {
                gridTemplateColumns: "1fr",
                paddingLeft: "12px",
                paddingRight: "12px", 
            },
            ['full']: {
                gridTemplateColumns: "1fr"
            },
            ['60-40']: {
                gridTemplateColumns: "0.6fr 0.4fr",
                gap: "max(8%, 64px)",
            },
            ['70-30']: {
                gridTemplateColumns: "0.7fr 0.3fr",
                gap: "max(4%, 40px)",
            },
        }
    },
})





const Home: NextPage = () => {
  return (
      <>
        <Head>
          <title>BrightData </title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Shell>
            <Box css={{ /* boxShadow: "inset -1px 0px #E0E3E6" */ }}/>
            <Page>
                <Section css={{ boxShadow: "inset 0px -1px #E0E3E6" }}>
                    <Content layout="full">
                        {/* <Box css={{ height: "120px" }} /> */}
                        <Nav/>
                    </Content>
                </Section>
                <Section>
                    <Content layout="overflow">
                        {/* <Box css={{ height: "400px" }}/> */}
                        <Table/>
                    </Content>
                </Section>
                <Section>
                    <Content layout="70-30">
                        {/* <Box css={{ height: "600px" }}/>
                        <Box css={{ height: "300px" }} /> */}
                        <Cards/>
                        <LinkList/>
                    </Content>
                </Section>
                <Section>
                    <Content layout="60-40">
                        <Cards/>
                        <LinkList/>
                    </Content>
                </Section>
            </Page>
        </Shell>
      </>
  )
}

export default Home
